### PR TITLE
.txt file to .MD file

### PR DESCRIPTION
**Pull request by matheuswd**
Just changing .txt file to .MD file to look better in Github.

### CODE REVIEW

**Comment by Viper007Bond** [comment]
As this is a WordPress plugin, I believe a `readme.txt` is required for WordPress.org plugin directory purposes.

I think it'd be a much better idea to make a separate `README.md` file that's tailored to GitHub and strips out everything but a description of the plugin. We don't need the changelog, all of the meta information (tested up to, contributors, etc.) cluttering up GitHub.

**Comment by matheuswd** [comment]
It's **separated**! Thanks for the tip

**Comment by Viper007Bond** [comment]
Thanks!

I'll defer to @iandunn on the wording and such used and whether he wants to modify it or what as this has been his baby recently.

**Comment by iandunn** [comment]
Since the audience for GitHub is developers who would potentially like to contribute, I think it'd be better to create the README.md from scratch, with information for that audience, rather than mirroring `readme.txt`, which is aimed at end users.

That way it's more of the information developers are interested in, and we don't have to worry about keeping the two in sync when things are changed.

What kinds of information would be helpful to devs? Just brainstorming here:

* A brief overview of what the plugin does (this can just be copied from readme.txt)
* How to run Grunt to build the bundled JavaScript
* Contributing

What else can you think of?

**Comment by matheuswd** [comment]
As you've said, @iandunn , we can use a 
* A brief overview (like a Project Description)
* How to run Grunt to build the bundled JavaScript
* Contributing

And we can add too
* Bugs and Suggestions

We could start with this and working in new version, if is necessary :smile: 

What do you think?

**Comment by iandunn** [comment]
That sounds good, thanks @matheuswd.

**Comment by matheuswd** [comment]
Can I help this README development? @iandunn

**Comment by iandunn** [comment]
Yeah, I think the next step would be to update the PR with a rough draft, and then we can review that and make any tweaks, and then merge it. Thanks :)

**Comment by matheuswd** [comment]
OK! I'll do it as soon as possible!

**Pull request closed without merging**
